### ISSUE TITLE
No Login after update

### ISSUE THREAD

**Issue by jeracom** [Birkbjo/OctoPrint-Themeify#7]
After I've updated the plugin, login is no longer possible.

**Comment by jeracom** [comment]
After I put the system on again, and no
update made. I uninstalled and reinstalled, then the plugin works.

**Comment by Birkbjo** [comment]
Thanks, I will look into that plugin!

**Comment by Birkbjo** [comment]
I'm sorry, I had a small bug which should now be fixed. Sorry for the bad version.

**Comment by jeracom** [comment]
No problem.
At least I had that in connection with the plugin Anywhere. It may be that it still appears with other plugins.

Greetings, Jens

**Comment by Birkbjo** [comment]
Did you get it to work with that plugin?

**Comment by jeracom** [comment]
Ok, if it works, it looks good :-)
![octo-theme](https://user-images.githubusercontent.com/5413676/33102547-8b6a4de6-cf1d-11e7-9c39-536b29b9aa38.jpg)

**Comment by Birkbjo** [comment]
Did you update to 0.3.1 and still not working with "Anyhwere"? I tried to install it and it worked fine for me with the new version.

**Comment by jeracom** [comment]
No.
Try it again. I then reports ...

**Comment by jeracom** [comment]
Ok, seems to work with  "Anywhere". 
I'll do some more tests tomorrow.

Greetings, Jens

**Comment by jeracom** [comment]
So far no errors have occurred. I'll close deb mistake times.

Greetings, Jens
